### ISSUE TITLE
TAL:OMIT-TAG not working properly in customised templates

### ISSUE THREAD

**Issue by lzdych** [plone/plone.app.themingplugins#2]
If the "tal:omit-tag" condition is used inside overridden template and its condition is True then it omits the whole tag including it's contents... so it works very the same like "tal:condition".

**Comment by frisi** [comment]
using the current release (1.0) the following snippet

```xhtml
<span class="foo" tal:omit-tag="python:True"><span class="bar">afasdf</span></span>
```

results in the following code on my rendered site:
```xhtml
<span class="bar">afasdf</span>
```
so omit-tag is working as expected.
maybe you're using [five.pt](https://pypi.python.org/pypi/five.pt) and discovered a but there?
