### ISSUE TITLE
customizing view directory and views.cfg not working

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.themingplugins#4]
According to the README, it should be possible to change the name of the views directory under `[theme:views]` in the `manifest.cfg` file, but this does not seem to work.
Also, the `views.cfg` file seems to be ignored.

**Comment by frisi** [comment]
in release 1.0b1 (latest release on pypi) the plugin did not correctly parse the configuration.
this has been fixed in https://github.com/plone/plone.app.themingplugins/commit/914546c3b3c9bf65e50254057836564cad7ec9d6 but there is no release yet.

**Comment by frisi** [comment]
@optilude can you create a new release (i'd go for a 1.0 final) on pypi or grant me permission to do so?

**Comment by optilude** [comment]
Assuming you're `frisi` on PyPI, you now have the power.

**Comment by frisi** [comment]
thanks @optilude!
 @fulv: you can try out 1.0 release now.
